export enum TransactionStatus {
  WAITING_FOR_PAYMENT = 'WAITING_FOR_PAYMENT',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  SHIPPING = 'SHIPPING',
  COMPLETED = 'COMPLETED',
  DISPUTED = 'DISPUTED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED', // <<< เพิ่มบรรทัดนี้
}